name: synx


on:
   schedule:
     # - cron : '00 09 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          issues: write
          
    steps:
      - uses: actions/checkout@v3
  
      # remote
      - name: remote upstream
        run : |
              git remote add upstream https://github.com/microsoft/Web-Dev-For-Beginners.git
              git remote -v
              
        # checkout
      - name : checkout
        run : git checkout -b english
        
      # fetch
      - name : fetch upstream
        run : git fetch upstream 
              
      # main의 최신 id               
      - name : main id
        run : git rev-parse main | read main_id
      
      # upstream/main의 최신 id
      - name : upstream id
        run : git rev-parse upstream/main | read upstream_id
        
        
      # main_id, upstream_id 같은지 확인
      - name : check version   
        shell : bash
        run : |
              if [ $main_id = $upstream_id ]; then                       # already up-to-date
                echo "state = true" >> $GITHUB_ENV   
                echo "already up-to-date"
              else                                                       # need to update
                echo "state = false" >> $GITHUB_ENV  
                echo "need to update"
              fi
      
      
              
      - name : git action
        if : ${{env.state == 'false'}}    # main_id, upstream_id 다르면 실행
        run : | 
              git merge upstream/main
              git push origin main
              git status
              
              echo "finish"
